[workspace]
resolver = "2"
members = [ "agent", "central-command","core-logic"]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = []

[workspace.dependencies]
core-logic = { path = "core-logic" }
chrono = { version = "0.4.23", features = ["serde"] }
log = { version = "0.4.27"  }
tokio = { version = "1.45", features = ["full"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.16.0", features = ["v4"] }
rkyv = { version = "0.8.10" }