[package]
name = "core-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
bson.workspace = true
chrono.workspace = true
futures.workspace = true
mongodb.workspace = true
tracing.workspace = true
serde.workspace = true
tokio.workspace = true
rkyv.workspace = true
uuid.workspace = true
