[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
core-logic.workspace = true
hostname.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
log.workspace = true
rkyv.workspace = true